### ISSUE TITLE
Allow customisable log file emplacement

### ISSUE THREAD

**Issue by slubman** [breca/elite_bgs_companion#31]
On windows one can change the "Saved Games" folder location, as such mine is located on a different disk than my user profile.
Because of this, the application cannot find the Elite Log files.

Would it be possible to have an option to set a custom location in the settings.ini for this situation?

**Comment by breca** [comment]
As per line https://github.com/breca/elite_bgs_companion/blob/c0680c964780bccd327770f85353291cae8870c2/BGS%20Companion.py#L90 the application now uses your %USERPROFILE% to find your save games folder

Please confirm you're on the latest release

**Comment by breca** [comment]
#30 #28

**Comment by slubman** [comment]
You’re right. I was using version 0.91

However now using version 0.93,
I get the following errors in the log:

```
2018-10-03 07:14:38,235 - root - INFO - Started.
2018-10-03 07:14:38,519 - root - INFO - Initialsing DataBroker
2018-10-03 07:14:38,520 - root - INFO - Checking database setup.
2018-10-03 07:14:38,523 - root - INFO - Database OK.
2018-10-03 07:14:38,523 - root - INFO - Initalising MessageMonitor
2018-10-03 07:14:38,523 - root - INFO - Initialsing JournalMonitor
2018-10-03 07:14:38,523 - root - INFO - Initialsing EDDN dispatcher.
2018-10-03 07:14:38,524 - root - INFO - Starting threads and configuring session.
2018-10-03 07:14:38,524 - root - INFO - Fetching session data from DB.
2018-10-03 07:14:38,524 - root - INFO - Updating runtime with previous session data.
2018-10-03 07:14:38,526 - root - ERROR - JournalMonitor hit exception checking for file.
max() arg is an empty sequence
Traceback (most recent call last):
  File "BGS Companion.py", line 864, in monitor_journal
ValueError: max() arg is an empty sequence
2018-10-03 07:14:38,527 - root - ERROR - EDDN Dispatcher encountered error trying to post Shipyard data.
max() arg is an empty sequence
Traceback (most recent call last):
  File "lib\eddn_sender.py", line 59, in shipyard_monitor
ValueError: max() arg is an empty sequence
2018-10-03 07:14:38,529 - root - ERROR - EDDN Dispatcher exception during runtime.
max() arg is an empty sequence
Traceback (most recent call last):
  File "lib\eddn_sender.py", line 24, in run
  File "lib\eddn_sender.py", line 87, in shipyard_monitor
  File "lib\eddn_sender.py", line 59, in shipyard_monitor
ValueError: max() arg is an empty sequence
2018-10-03 07:14:38,829 - root - ERROR - Exception occured refreshing main window stat string variables.
Cannot specify ',' with 's'.
Traceback (most recent call last):
  File "BGS Companion.py", line 388, in session_stats_update
ValueError: Cannot specify ',' with 's'.
2018-10-03 07:14:40,528 - root - INFO - Checking for updates.
2018-10-03 07:14:40,529 - root - INFO - Checking for latest version.
2018-10-03 07:14:42,599 - root - INFO - This version is up to date.

```

**Comment by breca** [comment]
Well that is less than great. Looks like it's unable to find any files..
Can you confirm their presence by going to '%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous'?
Regardless I'll throw in a override or something to allow users to set their paths manually

**Comment by slubman** [comment]
I think there lies the issue.

From a Python 2.7 shell;
```
>>> from os import path, environ
>>> print path.join(environ.get("USERPROFILE") + '\\Saved Games\\Frontier Developments\\Elite Dangerous')
C:\Users\slubman\Saved Games\Frontier Developments\Elite Dangerous
```

In an Explorer Window, the path **%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous** resolve to **D:\slubman\Saved Games\Frontier Developments\Elite Dangerous**

And the correct path is the one returned by the Explorer, not the one returned by the python snippet

**Comment by breca** [comment]
Nice find. This is built in Python 3.6 but I'm guessing the behavior is the same

**Comment by breca** [comment]
Workaround implemented 375af1a72cb3cc8fd0233d60fa2764c874ccdca5

**Comment by breca** [comment]
Latest version should sort you out @slubman

**Comment by slubman** [comment]
I can confirm using the override option, now the journal is being found and loaded :-)

**Comment by breca** [comment]
excellent, hope you get some use out of it :smiley:
